[project]
authors = ["Surfer12 <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "anthropic_project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
# Runtime commands
run = "python anthropic_client.py"
install-cli = "bash anthropic_client_mojo/claudethink_install"
test = "pytest tests/"
build = "python setup.py build"
dev-install = "pip install -e ."

# Documentation commands
docs = "mkdocs serve"
docs-build = "mkdocs build"

# Development commands
lint = "flake8 anthropic_client/ anthropic_client_mojo/python_cli.py"
typecheck = "mypy anthropic_client/"
format = "black anthropic_client/ anthropic_client_mojo/python_cli.py"

# Mojo specific commands
mojo-test = "mojo run anthropic_client_mojo/tests.mojo"
mojo-build = "mojo build anthropic_client_mojo/main.mojo -o bin/claudethink_mojo"

[dependencies]
anthropic = ">=0.49.0,<0.50"
max = ">=25.2.0.dev2025030805,<26"
python-dotenv = ">=1.0.1,<2"
flake8 = ">=7.1.2,<8"
mypy = ">=1.15.0,<2"
pytest = ">=8.3.5,<9"
pip = ">=25.0.1,<26"
black = ">=24.2.0,<25"
mkdocs = ">=1.5.3,<2"
pytest-cov = ">=4.1.0,<5"

[target.dev.dependencies]
pytest = ">=8.3.5,<9"
black = ">=24.2.0,<25"
