[project]
name = "anthropic-client"
version = "0.1.0"
description = "Anthropic client with Mojo integration"
authors = ["Surfer12 <ryanoatsie@outlook.com>"]
channels = [
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "conda-forge"
]
platforms = ["osx-arm64"]

[dependencies]
# Core dependencies
anthropic = ">=0.49.0,<0.50"
openai = ">=1.65.5,<2"
python-dotenv = ">=1.0.1,<2"
pyyaml = ">=6.0.1,<7"
rich = ">=13.7.0,<14"

# HTTP and SSL
requests = ">=2.32.3,<3"
httpx = ">=0.28.1,<0.29"
certifi = ">=2025.1.31,<2026"

# ML and data processing
sentence-transformers = "*"
numpy = ">=1.26.4,<2"
networkx = ">=3.2.1,<4"
nltk = ">=3.8.1,<4"
scipy = ">=1.12.0,<2"
pandas = ">=2.2.1,<3"

# Development dependencies
pytest = ">=8.3.5,<9"
pytest-cov = ">=6.0.0,<7"
black = ">=25.1.0,<26"
flake8 = ">=7.1.2,<8"
mypy = ">=1.15.0,<2"
mkdocs = ">=1.6.1,<2"

# Mojo/Max dependencies
max = ">=25.2.0.dev2025031605,<26"
pip = ">=25.0.1,<26"

[tasks]
# Build tasks
build = { cmd = "python setup.py build" }
install = { cmd = "pip install -e ." }
install-dev = { cmd = "pip install -e '.[dev]'" }

# Test tasks
test = { cmd = "pytest tests/" }
test-cov = { cmd = "pytest --cov=anthropic_client tests/" }

# Lint tasks
lint = { cmd = "flake8 anthropic_client/" }
format = { cmd = "black anthropic_client/" }
typecheck = { cmd = "mypy anthropic_client/" }

# Documentation tasks
docs = { cmd = "mkdocs serve" }
docs-build = { cmd = "mkdocs build" }

# Mojo tasks
mojo-build = { cmd = "mojo build src/mojo/main.mojo -o bin/anthropic_client" }
mojo-test = { cmd = "mojo run src/mojo/tests.mojo" }

[pypi-dependencies]
anthropic-client = { path = ".", editable = true } 