[project]
authors = ["Surfer12 <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "anthropic_project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
# Runtime commands
run = "python anthropic_client.py"
install-cli = "bash anthropic_client_mojo/claudethink_install"
test = "pytest tests/"
build = "python setup.py build"
osx-arm64-install = "pip install -e ."

# Documentation commands
docs = "mkdocs serve"
docs-build = "mkdocs build"

# Development commands
lint = "flake8 anthropic_client/ anthropic_client_mojo/python_cli.py"
typecheck = "mypy anthropic_client/"
format = "black anthropic_client/ anthropic_client_mojo/python_cli.py"

# Mojo specific commands
mojo-test = "mojo run anthropic_client_mojo/tests.mojo"
mojo-build = "mojo build anthropic_client_mojo/main.mojo -o bin/claudethink_mojo"

[dependencies]
anthropic = ">=0.49.0,<0.50"
max = ">=25.2.0.dev2025031005,<26"
python-dotenv = ">=1.0.1,<2"
flake8 = ">=7.1.2,<8"
mypy = ">=1.15.0,<2"
pytest = ">=8.3.5,<9"
pip = ">=25.0.1,<26"
black = ">=25.1.0,<26"
mkdocs = ">=1.6.1,<2"
pytest-cov = ">=6.0.0,<7"
openai = ">=1.65.5,<2"

# For dev dependencies that aren't platform-specific
[tool.pytest.dependencies]
pytest = ">=8.3.5,<9"

# For platform-specific dependencies
[target.osx-arm64.dependencies]
# Your Mac-specific dependencies here
