[project]
authors = ["Surfer12 <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "anthropic_client_mojo"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pip = ">=25.0.1,<26"
python-dotenv = ">=1.0.1,<2"
max = ">=25.2.0.dev2025030405,<26"
anthropic = ">=0.49.0,<0.50"
